name: myo
version: 0.1.1.0
synopsis: neovim layout & command manager
description: Please see the README on GitHub at <https://github.com/tek/myo-hs>
github: "tek/myo-hs"
license: MIT
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "tek@tryp.io"
copyright: "2018 Torsten Schmits"
category: Neovim
build-type: Simple

extra-source-files:
- README.md

dependencies:
- aeson
- attoparsec
- base-noprelude >= 4.7 && < 5
- bytestring
- chiasma
- composition-extra
- conduit
- conduit-extra
- containers
- cornea
- data-default
- deepseq
- directory
- either
- exceptions
- filepath
- free
- hourglass
- hslogger
- lens
- lifted-base
- messagepack
- monad-control
- mtl
- network
- nvim-hs
- parsec
- parsers
- path
- path-io
- prettyprinter
- process
- raw-strings-qq
- regex-with-pcre
- relude
- resourcet
- ribosome >= 0.3
- split
- stm-chans
- stm-conduit
- strings
- stringsearch
- text
- transformers
- transformers-base
- typed-process
- unix
- unliftio
- unliftio-core
- utf8-string
- uuid
- vector

library:
 source-dirs: lib

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- UnicodeSyntax
- ViewPatterns

executables:
 myo:
  main: Main.hs
  source-dirs: app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - myo

tests:
  myo-unit:
    main: SpecMain.hs
    source-dirs: test/u
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myo
    - ribosome-test
    - HTF
