name: myo
version: 0.1.1.0
synopsis: neovim layout & command manager
description: Please see the README on GitHub at <https://github.com/tek/myo>
github: tek/myo
license: BSD-2-Clause-Patent
author: Torsten Schmits
maintainer: tek@tryp.io
copyright: 2020 Torsten Schmits
category: Neovim
build-type: Simple

extra-source-files:
  - README.md

dependencies:
  - aeson
  - attoparsec
  - name: base
    version: '>= 4 && < 5'
    mixin:
      hiding (Prelude)
  - bytestring
  - chiasma
  - composition-extra
  - conduit
  - conduit-extra
  - containers
  - cornea
  - data-default
  - deepseq
  - directory
  - either
  - exceptions
  - filepath
  - free
  - hashable
  - hourglass
  - hslogger
  - lens
  - lifted-base
  - messagepack
  - monad-control
  - mono-traversable
  - mtl
  - neat-interpolation
  - network
  - nvim-hs
  - parsec
  - parsers
  - path
  - path-io
  - prettyprinter
  - process
  - raw-strings-qq
  - rawstring-qm
  - regex-with-pcre
  - relude
  - resourcet
  - ribosome >= 0.3
  - split
  - stm-chans
  - stm-conduit
  - strings
  - stringsearch
  - template-haskell
  - text
  - transformers
  - transformers-base
  - typed-process
  - unix
  - unliftio
  - unliftio-core
  - utf8-string
  - uuid
  - vector

library:
  source-dirs: lib

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wredundant-constraints

executables:
 myo:
  main: Main.hs
  source-dirs: app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - myo

tests:
  myo-unit:
    main: SpecMain.hs
    source-dirs: test/u
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myo
    - ribosome-test
    - HTF
